kafka:
  bootstrap:
    servers: localhost:9092
  consumer:
    group: stats.aggregator.action
    poll:
      timeout: 100
  topics:
    stats-user-action-v1: stats.user-actions.v1
    stats-events-similarity-v1: stats.events-similarity.v1